apiVersion: v1
kind: Secret
metadata:
  name: awssecret
type: Opaque
data:
  providerAccessKeyId: QUtJQTZQRlJWTUlFUUJSREdDSFI=
  providerSecretAccessKey: cVluUjR5UmZTT2FnMklFTWhVaUEvMHNsYW5KVEFCUHpFWUtxc29yWQ==