apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-reverseproxy
  labels:
    app: backend-reverseproxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-reverseproxy
  template:
    metadata:
      labels:
        app: backend-reverseproxy
    spec:
      containers:
      - name: backend-reverseproxy
        image: nambs97/reverseproxy
        ports:
        - containerPort: 8080
        env:
          - name: POSTGRES_USERNAME
            valueFrom:
              secretKeyRef:
                name: envsecret
                key: POSTGRES_USERNAME
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: envsecret
                key: POSTGRES_PASSWORD
          - name: POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: envconfig
                key: POSTGRES_HOST
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: envconfig
                key: POSTGRES_DB
          - name: AWS_BUCKET
            valueFrom:
              configMapKeyRef:
                name: envconfig
                key: AWS_BUCKET
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: envconfig
                key: AWS_REGION
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: envsecret
                key: JWT_SECRET
          - name: URL
            valueFrom:
              configMapKeyRef:
                name: envconfig
                key: URL